{
 "title": "export",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "strom_arbeitspreis", "label": "€ / kWh", "query": "0.2678" },
   { "name": "strom_grundgebuehr", "label": "Grundgebühr €", "query": "14.88" },
   { "name": "strom_verbrauch", "label": "kWh/Y", "query": "4400" }
  ]
 },
 "panels": [
  { "title": "Solar Now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energy Distribution",
   "type": "larona-epict-panel",
   "description": "solar rgb(253, 151, 0)\nhome rgb(69, 158, 149)\nbattery rgb(240, 95, 141)\ngrid rgb(72, 143, 194)",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(anker_solix_api_sites_grid_info_grid_to_home_power+anker_solix_api_sites_solarbank_info_to_home_load-anker_solix_api_sites_grid_info_photovoltaic_to_grid_power)",
     "legendFormat": "home load"
    },
    {
     "expr": "anker_solix_api_sites_solarbank_info_total_photovoltaic_power",
     "legendFormat": "solar power"
    },
    {
     "expr": "anker_solix_api_sites_solarbank_info_total_charging_power",
     "legendFormat": "battery power in"
    },
    {
     "expr": "(anker_solix_api_sites_solarbank_info_total_charging_power*-1)",
     "legendFormat": "battery out"
    },
    {
     "expr": "anker_solix_api_sites_grid_info_grid_to_home_power",
     "legendFormat": "grid in"
    },
    {
     "expr": "anker_solix_api_sites_grid_info_photovoltaic_to_grid_power",
     "legendFormat": "grid out"
    },
    {
     "expr": "anker_solix_api_sites_solarbank_info_solarbank_list_value_0_battery_power",
     "legendFormat": "battery level"
    },
    {
     "expr": "anker_solix_api_sites_solarbank_info_total_photovoltaic_power - anker_solix_api_sites_solarbank_info_total_charging_power - anker_solix_api_sites_grid_info_photovoltaic_to_grid_power",
     "legendFormat": "solar_2_home"
    },
    {
     "expr": "anker_solix_api_sites_solarbank_info_solar_power_1",
     "legendFormat": "panel_1"
    },
    {
     "expr": "anker_solix_api_sites_solarbank_info_solar_power_2",
     "legendFormat": "panel_2"
    },
    {
     "expr": "anker_solix_api_sites_solarbank_info_solar_power_3",
     "legendFormat": "panel_3"
    },
    {
     "expr": "anker_solix_api_sites_solarbank_info_solar_power_4",
     "legendFormat": "panel_4"
    }
   ]
  },
  {
   "title": "Power Shares  now",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_sites_grid_info_grid_to_home_power+anker_solix_api_sites_solarbank_info_to_home_load- anker_solix_api_sites_smart_plug_info_total_power)",
     "legendFormat": "House"
    },
    {
     "expr": "sum by (alias) (anker_solix_api_devices_current_power)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Power Share Averages",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_sites_grid_info_grid_to_home_power+anker_solix_api_sites_solarbank_info_to_home_load- anker_solix_api_sites_smart_plug_info_total_power)\n",
     "legendFormat": "House"
    },
    {
     "expr": "sum by (alias) (anker_solix_api_devices_current_power)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Autarky Grade",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_sites_energy_details_today_solar_production  -  anker_solix_api_sites_energy_details_today_solar_to_grid) / sum(anker_solix_api_sites_energy_details_today_home_usage) or sum(anker_solix_api_energy_today_home_usage) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Charging Status",
   "type": "stat",
   "description": "- detection = \"0\"  # frequent for  Smartmeter in the morning\n- protection_charge = \"03\"  # when there is charge while output below demand in detection mode\n- bypass = \"1\" # Bypass solar without charging\n- bypass_discharge = \"12\"  # if discharging in bypass mode\n- discharge = \"2\"  # only seen if no solar available\n- charge = \"3\"  # normal charge for battery\n- charge_bypass = \"31\"  # unused\n- charge_priority = \"37\"  # unused\n- wakeup = \"4\"  # Not clear short intervals during night, probably hourly? resync with the cloud\n- unknown = \"5\" # was not observed yet\n- full_bypass = \"6\"  # at cold temperature, when battery must not be charged and the Solarbank bypasses all directly to inverter, also solar power < 25 W\n- standby = \"7\"",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_devices_charging_status)",
     "legendFormat": "Charging Status"
    }
   ]
  },
  {
   "title": "House without Plugs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_sites_grid_info_grid_to_home_power+anker_solix_api_sites_solarbank_info_to_home_load- anker_solix_api_sites_smart_plug_info_total_power)\n",
     "legendFormat": "AstromaX"
    }
   ]
  },
  {
   "title": "Production Prediction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "anker_solix_api_sites_energy_details_today_solar_production*1000",
     "legendFormat": "Reality"
    },
    {
     "expr": "anker_solix_api_sites_energy_details_today_home_usage*1000",
     "legendFormat": "Usage"
    },
    {
     "expr": "anker_solix_api_sites_energy_details_today_grid_to_home*1000",
     "legendFormat": "Imported"
    },
    {
     "expr": "anker_solix_api_sites_energy_details_today_solar_to_grid*1000",
     "legendFormat": "Exported"
    }
   ]
  },
  { "title": "Solar Stats in Time Range", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Home Energy Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_sites_grid_info_grid_to_home_power)",
     "legendFormat": "Grid"
    },
    {
     "expr": "sum(anker_solix_api_sites_solarbank_info_to_home_load)",
     "legendFormat": "Battery or Solar"
    }
   ]
  },
  {
   "title": "Home Energy Sources",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_today_solarbank_charge) or sum(anker_solix_api_sites_energy_details_today_solarbank_charge) or sum(anker_solix_api_sites_energy_details_today_battery_charge)",
     "legendFormat": "Battery"
    },
    {
     "expr": "sum(anker_solix_api_sites_energy_details_today_grid_to_home)",
     "legendFormat": "Grid"
    },
    {
     "expr": "sum(anker_solix_api_sites_energy_details_today_solar_production) -sum(\n    anker_solix_api_sites_energy_details_today_battery_charge or anker_solix_api_today_solarbank_charge\n) -  sum(anker_solix_api_sites_energy_details_today_solar_to_grid)",
     "legendFormat": "Solar"
    }
   ]
  },
  {
   "title": "Solaroutput Expectation and reality",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "pvgis_api_seriescalc_min", "legendFormat": "Min" },
    { "expr": "pvgis_api_seriescalc_avg", "legendFormat": "Avg" },
    {
     "expr": "anker_solix_api_sites_solarbank_info_total_photovoltaic_power offset  -60m",
     "legendFormat": "Reality"
    },
    {
     "expr": "sum(anker_solix_api_sites_grid_info_grid_to_home_power+anker_solix_api_sites_solarbank_info_to_home_load- anker_solix_api_sites_smart_plug_info_total_power)\n",
     "legendFormat": "Power Usage"
    }
   ]
  },
  {
   "title": "Solar Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_sites_grid_info_photovoltaic_to_grid_power)",
     "legendFormat": "Grid"
    },
    {
     "expr": "sum(anker_solix_api_sites_solarbank_info_pei_heating_power)",
     "legendFormat": "Heating Power"
    },
    {
     "expr": "sum(anker_solix_api_sites_solarbank_info_total_charging_power) >= 0",
     "legendFormat": "Battery"
    },
    {
     "expr": "sum(anker_solix_api_sites_solarbank_info_total_photovoltaic_power) - \n(sum(anker_solix_api_sites_solarbank_info_total_charging_power) >= 0 )",
     "legendFormat": "Home"
    }
   ]
  },
  {
   "title": "Panel Production Shares",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_today_solar_production_pv1) or sum(anker_solix_api_sites_energy_details_today_solar_production_pv1)",
     "legendFormat": "PV1"
    },
    {
     "expr": "sum(anker_solix_api_today_solar_production_pv2) or sum(anker_solix_api_sites_energy_details_today_solar_production_pv2)",
     "legendFormat": "PV2"
    },
    {
     "expr": "sum(anker_solix_api_today_solar_production_pv3) or sum(anker_solix_api_sites_energy_details_today_solar_production_pv3)",
     "legendFormat": "PV3"
    },
    {
     "expr": "sum(anker_solix_api_today_solar_production_pv4) or sum(anker_solix_api_sites_energy_details_today_solar_production_pv4)",
     "legendFormat": "PV4"
    }
   ]
  },
  {
   "title": "Solar Panels",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_solarbank_info_solar_power_1) or sum(anker_solix_api_sites_solarbank_info_solar_power_1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(anker_solix_api_solarbank_info_solar_power_2) or sum(anker_solix_api_sites_solarbank_info_solar_power_2)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(anker_solix_api_solarbank_info_solar_power_3) or sum(anker_solix_api_sites_solarbank_info_solar_power_3)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(anker_solix_api_solarbank_info_solar_power_4) or sum(anker_solix_api_sites_solarbank_info_solar_power_4)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grid Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_sites_grid_info_grid_to_home_power)",
     "legendFormat": "Import"
    },
    {
     "expr": "sum(anker_solix_api_sites_grid_info_photovoltaic_to_grid_power)",
     "legendFormat": "Export"
    }
   ]
  },
  {
   "title": "Solar Power Destinations",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_today_solarbank_charge) or sum(anker_solix_api_sites_energy_details_today_solarbank_charge) or sum(anker_solix_api_sites_energy_details_today_battery_charge)",
     "legendFormat": "Battery"
    },
    {
     "expr": "sum(anker_solix_api_sites_energy_details_today_solar_to_grid)",
     "legendFormat": "Grid"
    },
    {
     "expr": "sum(anker_solix_api_sites_energy_details_today_solar_production) -sum(\n    anker_solix_api_sites_energy_details_today_battery_charge or anker_solix_api_today_solarbank_charge\n) -  sum(anker_solix_api_sites_energy_details_today_solar_to_grid)",
     "legendFormat": "Home"
    }
   ]
  },
  {
   "title": "Battery State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_value0_battery_power or anker_solix_api_sites_solarbank_info_solarbank_list_value_0_battery_power)/100",
     "legendFormat": "Charge"
    }
   ]
  },
  {
   "title": "Charging Status",
   "type": "timeseries",
   "description": "- detection = \"0\"  # frequent for  Smartmeter in the morning\n- protection_charge = \"03\"  # when there is charge while output below demand in detection mode\n- bypass = \"1\" # Bypass solar without charging\n- bypass_discharge = \"12\"  # if discharging in bypass mode\n- discharge = \"2\"  # only seen if no solar available\n- charge = \"3\"  # normal charge for battery\n- charge_bypass = \"31\"  # unused\n- charge_priority = \"37\"  # unused\n- wakeup = \"4\"  # Not clear short intervals during night, probably hourly? resync with the cloud\n- unknown = \"5\" # was not observed yet\n- full_bypass = \"6\"  # at cold temperature, when battery must not be charged and the Solarbank bypasses all directly to inverter, also solar power < 25 W\n- standby = \"7\"",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(anker_solix_api_devices_charging_status)",
     "legendFormat": "Charging Status"
    }
   ]
  },
  {
   "title": "Grid Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(anker_solix_api_sites_energy_details_today_solar_to_grid)",
     "legendFormat": "Export"
    },
    {
     "expr": "sum(anker_solix_api_sites_energy_details_today_grid_to_home)",
     "legendFormat": "Import"
    }
   ]
  },
  {
   "title": "Power Share Averages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (alias) (anker_solix_api_devices_current_power)",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}