name: Release on Commit

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set date tag
        run: |
          DATE_TAG=$(date +'%Y.%m.%d_%H%M%S')
          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV

      - name: Get changed files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | sed 's/^/- /')
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATE_TAG }}
          name: Release ${{ env.DATE_TAG }}
          body: |
            ## Changed files
            ${{ env.CHANGED_FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
