name: Release on Commit
permissions:
  contents: write
  pull-requests: write
  
on:
  workflow_run:
    workflows: ["Build and Publish Multi-Arch Docker Image"]  # name of the Docker workflow
    types:
      - completed
  push:
    branches:
      - master

jobs:
  release:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set date tag
        id: tag
        run: |
          DATE_TAG=$(date +'%Y.%m.%d_%H%M%S')
          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATE_TAG }}
          name: Release ${{ env.DATE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
